/**
 * Design tokens are split into raw values, semantic roles, and component recipes.
 * Exact palette values can change, but screens must keep using semantic roles.
 */

export const rawTokens = {
  palette: {
    brand: {
      legacy: '#08090A',
      legacyDark: '#282B30',
      legacyLight: '#F4F5F7',
      500: '#08090A',
      600: '#08090A',
      700: '#282B30',
    },
    neutral: {
      0: '#FFFFFF',
      25: '#FAFAFB',
      50: '#F4F5F7',
      100: '#E7E9ED',
      200: '#DDE0E5',
      300: '#C8CCD3',
      500: '#686D76',
      600: '#484C54',
      700: '#282B30',
      900: '#08090A',
      1000: '#000000',
    },
    risk: {
      critical: '#B42318',
      medium: '#B54708',
      low: '#7A5F00',
      noRuleHit: '#067647',
    },
    statusSurface: {
      error: '#FEF3F2',
      warning: '#FFFAEB',
      info: '#EFF8FF',
      success: '#ECFDF3',
    },
    legacyRisk: {
      critical: '#E63946',
      medium: '#F4A261',
      low: '#FFD23F',
      safe: '#06D6A0',
    },
  },
  space: {
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
    8: 32,
    10: 40,
    12: 48,
  },
  fontSize: {
    caption: 12,
    label: 14,
    body: 16,
    titleSmall: 20,
    title: 24,
    titleLarge: 28,
    display: 36,
    legacyLarge: 48,
    legacyHero: 64,
  },
  lineHeight: {
    caption: 18,
    label: 22,
    body: 24,
    titleSmall: 28,
    title: 32,
    titleLarge: 36,
    display: 44,
  },
  radius: {
    small: 6,
    medium: 10,
    large: 12,
    xlarge: 16,
    round: 999,
  },
  size: {
    touchMinimum: 44,
    inputMinimum: 48,
    primaryControl: 52,
  },
  duration: {
    fast: 120,
    normal: 200,
    scan: 650,
  },
} as const;

export const semanticColors = {
  surface: {
    page: rawTokens.palette.neutral[0],
    subtle: rawTokens.palette.neutral[50],
    muted: rawTokens.palette.neutral[100],
    inverse: rawTokens.palette.neutral[900],
    accentSubtle: rawTokens.palette.neutral[50],
    errorSubtle: rawTokens.palette.statusSurface.error,
    warningSubtle: rawTokens.palette.statusSurface.warning,
    infoSubtle: rawTokens.palette.statusSurface.info,
    successSubtle: rawTokens.palette.statusSurface.success,
    glass: 'rgba(255, 255, 255, 0.92)',
    glassSubtle: 'rgba(255, 255, 255, 0.08)',
    lens: 'rgba(255, 255, 255, 0.12)',
    scrim: 'rgba(8, 9, 10, 0.72)',
  },
  text: {
    primary: rawTokens.palette.neutral[900],
    secondary: rawTokens.palette.neutral[600],
    muted: rawTokens.palette.neutral[500],
    action: rawTokens.palette.neutral[900],
    inverse: rawTokens.palette.neutral[0],
    onAction: rawTokens.palette.neutral[0],
    error: rawTokens.palette.risk.critical,
    warning: rawTokens.palette.risk.medium,
    info: '#175CD3',
    success: rawTokens.palette.risk.noRuleHit,
  },
  action: {
    primary: rawTokens.palette.neutral[900],
    primaryPressed: rawTokens.palette.neutral[700],
    secondaryPressed: rawTokens.palette.neutral[50],
    decorativeAccent: rawTokens.palette.neutral[900],
    disabledBackground: rawTokens.palette.neutral[200],
    disabledForeground: rawTokens.palette.neutral[500],
  },
  border: {
    strong: rawTokens.palette.neutral[900],
    default: rawTokens.palette.neutral[300],
    subtle: rawTokens.palette.neutral[200],
    focus: rawTokens.palette.neutral[900],
    onInverse: 'rgba(255, 255, 255, 0.82)',
    error: rawTokens.palette.risk.critical,
    warning: rawTokens.palette.risk.medium,
  },
  status: {
    error: rawTokens.palette.risk.critical,
    warning: rawTokens.palette.risk.medium,
    info: '#175CD3',
    noRuleHit: rawTokens.palette.risk.noRuleHit,
  },
  risk: {
    critical: rawTokens.palette.risk.critical,
    medium: rawTokens.palette.risk.medium,
    low: rawTokens.palette.risk.low,
    noRuleHit: rawTokens.palette.risk.noRuleHit,
  },
  overlay: {
    photo: 'rgba(8, 9, 10, 0.58)',
    photoStrong: 'rgba(8, 9, 10, 0.74)',
    label: 'rgba(8, 9, 10, 0.92)',
    annotationCurrent: 'rgba(8, 9, 10, 0.10)',
    annotationUpcoming: 'rgba(104, 109, 118, 0.14)',
  },
} as const;

export const typographyTokens = {
  display: {
    fontSize: rawTokens.fontSize.display,
    lineHeight: rawTokens.lineHeight.display,
    fontWeight: '700' as const,
  },
  title: {
    fontSize: rawTokens.fontSize.title,
    lineHeight: rawTokens.lineHeight.title,
    fontWeight: '700' as const,
  },
  titleSmall: {
    fontSize: rawTokens.fontSize.titleSmall,
    lineHeight: rawTokens.lineHeight.titleSmall,
    fontWeight: '700' as const,
  },
  body: {
    fontSize: rawTokens.fontSize.body,
    lineHeight: rawTokens.lineHeight.body,
    fontWeight: '400' as const,
  },
  label: {
    fontSize: rawTokens.fontSize.label,
    lineHeight: rawTokens.lineHeight.label,
    fontWeight: '600' as const,
  },
  caption: {
    fontSize: rawTokens.fontSize.caption,
    lineHeight: rawTokens.lineHeight.caption,
    fontWeight: '400' as const,
  },
} as const;

export const componentTokens = {
  button: {
    minHeight: rawTokens.size.primaryControl,
    compactMinHeight: rawTokens.size.touchMinimum,
    radius: rawTokens.radius.large,
    horizontalPadding: rawTokens.space[5],
    gap: rawTokens.space[2],
  },
  surface: {
    radius: rawTokens.radius.large,
    padding: rawTokens.space[4],
    borderWidth: 1,
    strongBorderWidth: 2,
  },
  input: {
    minHeight: rawTokens.size.inputMinimum,
    radius: rawTokens.radius.medium,
    borderWidth: 1,
    horizontalPadding: rawTokens.space[3],
    verticalPadding: rawTokens.space[3],
    gap: rawTokens.space[2],
    multilineMinHeight: 96,
  },
  badge: {
    minHeight: rawTokens.space[6],
    radius: rawTokens.radius.round,
    horizontalPadding: rawTokens.space[3],
    verticalPadding: rawTokens.space[1],
    gap: rawTokens.space[1],
  },
  photo: {
    panoramaAspectRatio: 4 / 3,
    detailAspectRatio: 16 / 9,
    radius: rawTokens.radius.large,
    background: rawTokens.palette.neutral[900],
    wideMaxWidth: 520,
    annotationCurrentBorderWidth: 4,
    annotationUpcomingBorderWidth: 2,
    annotationMinimumSize: 24,
    annotationLabelHorizontalPadding: rawTokens.space[2],
    annotationLabelVerticalPadding: rawTokens.space[1],
  },
  progressSummary: {
    gap: rawTokens.space[3],
    padding: rawTokens.space[4],
  },
  stateMessage: {
    gap: rawTokens.space[3],
    padding: rawTokens.space[5],
  },
  recoveryPanel: {
    gap: rawTokens.space[3],
    padding: rawTokens.space[4],
    iconSize: rawTokens.size.touchMinimum,
    borderWidth: 2,
  },
  analysis: {
    maxWidth: 520,
    frameHeight: 264,
    targetWidth: 176,
    targetHeight: 112,
    statusIndexSize: rawTokens.space[8],
    scanLineWidth: 2,
  },
  report: {
    scoreRingSize: 96,
    scoreRingBorderWidth: 9,
    statMinHeight: 72,
    summaryBorderWidth: 2,
    summaryAccentWidth: 5,
  },
  shareCard: {
    aspectRatio: 3 / 4,
    previewMaxWidth: 360,
    padding: rawTokens.space[4],
    borderWidth: 2,
    scoreRingSize: 76,
    scoreRingBorderWidth: 7,
    statMinHeight: 52,
    summaryBorderWidth: 2,
    summaryAccentWidth: 5,
    ruleWidth: 2,
    outputWidth: 1080,
    outputHeight: 1440,
  },
} as const;
